"""Added tool column

Revision ID: 2305fb2d5947
Revises: fdcccaa75e55
Create Date: 2026-07-10 05:37:35.516643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2305fb2d5947'
down_revision = 'fdcccaa75e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.drop_column('tool')

    # ### end Alembic commands ###
