"""Added review metrics

Revision ID: 35fe16a117cf
Revises: 2305fb2d5947
Create Date: 2026-07-10 08:02:36.395592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fe16a117cf'
down_revision = '2305fb2d5947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintainability_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sloc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lloc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('multi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('blank')
        batch_op.drop_column('multi')
        batch_op.drop_column('comments')
        batch_op.drop_column('lloc')
        batch_op.drop_column('sloc')
        batch_op.drop_column('loc')
        batch_op.drop_column('maintainability_index')

    # ### end Alembic commands ###
