"""Add file fields to projects

Revision ID: fdcccaa75e55
Revises: c5fb8ed66616
Create Date: 2026-07-10 01:51:17.520040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcccaa75e55'
down_revision = 'c5fb8ed66616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
